# Generated by Django 6.0.6 on 2026-06-28 12:28

import cars.utils.upload_utils
import cars.validators
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cars', '0006_alter_brand_description_alter_carmodel_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên tỉnh/ thành phố')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'Tỉnh/Thành phố',
                'verbose_name_plural': 'Tỉnh/Thành phố',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
                ('bio', models.TextField(blank=True, help_text='Giới thiệu sản phẩm')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=cars.utils.upload_utils.UploadToPath(base_path='users', slug_field='username', sub_path='avatars'), validators=[cars.validators.validate_image_extension, cars.validators.validate_image_size])),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user_type', models.CharField(choices=[('customer', 'Khách hàng'), ('saler', 'Nhân viên tư vấn'), ('writer', 'Cộng tác viên')], default='customer', max_length=20)),
                ('phone_encrypted', models.TextField(blank=True)),
                ('phone_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('address_encrypted', models.TextField(blank=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('province', models.ForeignKey(blank=True, help_text='Tỉnh/Thành phố đang sinh sống', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.province')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Tên Showroom')),
                ('address', models.CharField(max_length=300, verbose_name='Địa chỉ chi tiết')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showrooms', to='cars.brand', verbose_name='Hãng xe')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='showrooms', to='users.province', verbose_name='Tỉnh/Thành phố')),
            ],
            options={
                'verbose_name': 'Showroom',
                'verbose_name_plural': 'Showroom',
            },
        ),
        migrations.CreateModel(
            name='SalerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=100, verbose_name='Mã Nhân Viên')),
                ('cccd_encrypted', models.TextField(blank=True)),
                ('cccd_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_verified', models.BooleanField(default=False, help_text='Admin xác minh trước khi hiển thị công khai')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saler_profile', to=settings.AUTH_USER_MODEL)),
                ('showroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salers', to='users.showroom', verbose_name='Showroom')),
            ],
            options={
                'verbose_name': 'Hồ sơ nhân viên tư vấn',
                'verbose_name_plural': 'Hồ sơ nhân viên tư vấn',
            },
        ),
        migrations.CreateModel(
            name='SavedCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='cars.carvariant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xe đã lưu',
                'verbose_name_plural': 'Xe đã lưu',
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'car')},
            },
        ),
    ]
