services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    image: ghcr.io/thanhthien176/car-website-project/web:latest
    env_file: .env.production
    command: gunicorn config.wsgi:application --config gunicorn.conf.py
    volumes:
      - /var/www/projectcarweb/static:/home/appuser/app/staticfiles
      - /var/www/projectcarweb/media:/home/appuser/app/media
      - /var/www/projectcarweb/logs:/home/appuser/app/logs
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  