# Generated by Django 6.0.6 on 2026-07-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('UNREAD', 'Chưa đọc'), ('PROCESSING', 'Đang xử lý'), ('DONE', 'Đã xử lý xong')], default='UNREAD', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xử lý xong')),
                ('resolution_note', models.TextField(blank=True, verbose_name='Ghi chú phản hồi')),
            ],
        ),
    ]
