# Generated by Django 6.0.6 on 2026-07-18 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactme',
            options={'verbose_name_plural': 'Contacts'},
        ),
    ]
