# Generated by Django 6.0.6 on 2026-08-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contactme_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteIdentify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(blank=True, help_text='Slogan of website', max_length=400)),
                ('og_title', models.CharField(blank=True, help_text='Tiêu đề hiển thị khi chia sẻ link', max_length=150)),
                ('og_description', models.CharField(blank=True, help_text='Mô tả ngắn khi chia sẻ link', max_length=300)),
                ('og_image', models.ImageField(help_text='Ảnh preview khi chia sẻ Social Media (Tỉ lệ chuẩn 1200x630)', upload_to='identify/og/')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
