# Generated by Django 6.0.6 on 2026-07-08 07:50

import cars.utils.upload_utils
import cars.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0006_alter_brand_description_alter_carmodel_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Blog Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_articles', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blogs.blogcategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blogs.blogtag')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
            },
        ),
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=cars.utils.upload_utils.UploadToPath('blogs', 'post_section', slug_field='post.slug'), validators=[cars.validators.validate_image_extension, cars.validators.validate_image_size])),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='blogs.blogpost')),
            ],
            options={
                'verbose_name': 'Blog Section',
                'verbose_name_plural': 'Blog Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BrandHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_articles', to=settings.AUTH_USER_MODEL)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='cars.brand')),
            ],
            options={
                'verbose_name': 'Brand History',
                'verbose_name_plural': 'Brand Histories',
            },
        ),
        migrations.CreateModel(
            name='BrandHistorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=cars.utils.upload_utils.UploadToPath('blogs', 'brand_history_sections', slug_field='history.brand.slug'), validators=[cars.validators.validate_image_extension, cars.validators.validate_image_size])),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='blogs.brandhistory')),
            ],
            options={
                'verbose_name': 'Brand History Section',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CarDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Bài chính trong nhóm (theo variant cụ thể, hoặc nhóm dùng chung nếu variant trống)')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_articles', to=settings.AUTH_USER_MODEL)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='cars.carmodel')),
                ('variant', models.ForeignKey(blank=True, help_text='Để trống nếu bài viết dùng chung cho mọi phiên bản của dòng xe này', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='cars.carvariant')),
            ],
            options={
                'verbose_name': 'Car Description',
                'verbose_name_plural': 'Car Descriptions',
                'ordering': ['-is_primary', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='CarDescriptionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=cars.utils.upload_utils.UploadToPath('blogs', 'car_description_sections', slug_field='description.image_slug'), validators=[cars.validators.validate_image_size, cars.validators.validate_image_extension])),
                ('desciption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='blogs.cardescription')),
            ],
            options={
                'verbose_name': 'Car Description Section',
                'ordering': ['order'],
            },
        ),
    ]
