# Generated by Django 6.0.6 on 2026-07-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.RenameField(
            model_name='cardescriptionsection',
            old_name='desciption',
            new_name='description',
        ),
    ]
