# Generated by Django 6.0.3 on 2026-05-14 05:42

import cars.utils.upload_utils
import cars.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='Tiêu đề hiển thị kết quả tìm kiếm(tối ưu <70 ký tự)', max_length=70)),
                ('seo_description', models.CharField(blank=True, help_text='Mô tả ngắn gọn về trang(tối ưu: 150-160 ký tự)', max_length=160)),
                ('seo_keyword', models.CharField(blank=True, help_text='Các từ khóa cách nhau bằng dấu phẩy', max_length=255)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('country_of_origin', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=cars.utils.upload_utils.UploadToPath('brand', 'logos'), validators=[cars.validators.validate_image_size, cars.validators.validate_image_extension])),
                ('description', models.TextField(blank=True, null=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='Tiêu đề hiển thị kết quả tìm kiếm(tối ưu <70 ký tự)', max_length=70)),
                ('seo_description', models.CharField(blank=True, help_text='Mô tả ngắn gọn về trang(tối ưu: 150-160 ký tự)', max_length=160)),
                ('seo_keyword', models.CharField(blank=True, help_text='Các từ khóa cách nhau bằng dấu phẩy', max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('car_slug', models.SlugField(blank=True, unique=True)),
                ('model_year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=cars.utils.upload_utils.UploadToPath('cars', 'thumbnail'), validators=[cars.validators.validate_image_size, cars.validators.validate_image_extension])),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('body_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.bodytype')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_models', to='cars.brand')),
                ('car_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carclass')),
            ],
            options={
                'verbose_name_plural': 'Car Models',
                'ordering': ['brand__name', 'name', '-model_year'],
            },
        ),
        migrations.CreateModel(
            name='CarVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='Tiêu đề hiển thị kết quả tìm kiếm(tối ưu <70 ký tự)', max_length=70)),
                ('seo_description', models.CharField(blank=True, help_text='Mô tả ngắn gọn về trang(tối ưu: 150-160 ký tự)', max_length=160)),
                ('seo_keyword', models.CharField(blank=True, help_text='Các từ khóa cách nhau bằng dấu phẩy', max_length=255)),
                ('variant_name', models.CharField(max_length=100)),
                ('variant_slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Xăng'), ('diesel', 'Diesel'), ('electric', 'Điện'), ('hybrid', 'Hybrid'), ('phev', 'Plug-in Hybrid')], max_length=20)),
                ('price_min', models.DecimalField(decimal_places=0, max_digits=15)),
                ('price_max', models.DecimalField(decimal_places=0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='cars.carmodel')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variants',
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=cars.utils.upload_utils.UploadToPath('cars', 'gallery'), validators=[cars.validators.validate_image_size, cars.validators.validate_image_extension])),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.carvariant')),
            ],
            options={
                'verbose_name': 'Car picture',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ComfortSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_conditioner', models.CharField(blank=True, help_text='Hệ thống điều hòa', max_length=20, null=True)),
                ('rear_air_duct', models.BooleanField(default=False, help_text='Cửa gió sau')),
                ('display', models.CharField(blank=True, help_text='Màn hình giải trí', max_length=30, null=True)),
                ('number_of_speaker', models.CharField(blank=True, help_text='Số loa', max_length=30, null=True)),
                ('smart_connect', models.CharField(blank=True, help_text='Kết nối không dây', max_length=30, null=True)),
                ('smart_key', models.BooleanField(default=False, help_text='Chìa khóa thông minh')),
                ('power_window', models.CharField(blank=True, help_text='Cửa sổ điều chỉnh điện', max_length=30, null=True)),
                ('power_back_door', models.BooleanField(default=False, help_text='Cốp điện')),
                ('cruise_control', models.BooleanField(default=False, help_text='Hệ thống điều khiển hành trình')),
                ('electric_parking_brake', models.BooleanField(default=False, help_text='Phanh tay điện tủ')),
                ('brake_hold', models.BooleanField(default=False, help_text='Giữ phanh tự động')),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comfort', to='cars.carvariant')),
            ],
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cars', models.ManyToManyField(related_name='comparisons', to='cars.carvariant')),
            ],
            options={
                'verbose_name': 'Car Comparison',
            },
        ),
        migrations.CreateModel(
            name='DimensionSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.PositiveIntegerField(blank=True, help_text='Chiều dài(mm)', null=True)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Chiều rộng(mm)', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='chiều cao(mm)', null=True)),
                ('wheelbase', models.PositiveIntegerField(blank=True, help_text='Chiều dài cơ sở(mm)', null=True)),
                ('ground_clearance', models.PositiveSmallIntegerField(blank=True, help_text='Khoảng sáng gầm xe(mm)', null=True)),
                ('seating_capacity', models.PositiveSmallIntegerField(blank=True, help_text='Số chỗ ngồi', null=True)),
                ('fuel_tank_capacity', models.PositiveSmallIntegerField(blank=True, help_text='Dung tích bình nhiên liệu(lít)', null=True)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dimension', to='cars.carvariant')),
            ],
        ),
        migrations.CreateModel(
            name='EngineSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(blank=True, max_length=100)),
                ('displacement', models.PositiveIntegerField(blank=True, help_text='Dung tích xi lanh(cc)', null=True)),
                ('max_power', models.PositiveIntegerField(blank=True, help_text='Công suất tối đa(Hp)', null=True)),
                ('max_torque', models.PositiveIntegerField(blank=True, help_text='Momen xoắn tối đa(Nm)', null=True)),
                ('drive_train', models.CharField(blank=True, help_text='Hệ số truyền động', max_length=30, null=True)),
                ('transmission', models.CharField(choices=[('automatic', 'Tự động'), ('manual', 'Số sàn'), ('cvt', 'CVT')], max_length=20)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engine', to='cars.carvariant')),
            ],
        ),
        migrations.CreateModel(
            name='ExteriorSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headlamp', models.CharField(blank=True, help_text='Đèn chiếu sáng trước', max_length=30, null=True)),
                ('daytime_running_light', models.BooleanField(default=False)),
                ('auto_light_control', models.BooleanField(default=False)),
                ('rearlamp', models.CharField(blank=True, help_text='Đèn hậu', max_length=30, null=True)),
                ('foglamp', models.CharField(blank=True, help_text='Đèn sương mù', max_length=30, null=True)),
                ('power_fold_mirror', models.BooleanField(default=False)),
                ('power_adjust_mirror', models.BooleanField(default=False)),
                ('turn_signal_lamp', models.BooleanField(default=False, help_text='Tích hợp đèn báo rẽ')),
                ('wiper_front', models.CharField(blank=True, help_text='Gạt mưa trước', max_length=30, null=True)),
                ('wiper_rear', models.CharField(blank=True, help_text='Gạt mưa sau', max_length=30, null=True)),
                ('rear_glass_defrogger', models.BooleanField(default=False, help_text='Chức năng sấy kính sau')),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exterior', to='cars.carvariant')),
            ],
        ),
        migrations.CreateModel(
            name='FuelConsumptionSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urban', models.DecimalField(blank=True, decimal_places=2, help_text='Trong đô thị(lit/100km)', max_digits=4, null=True)),
                ('extra_urban', models.DecimalField(blank=True, decimal_places=2, help_text='Ngoài đô thị(lít/100km)', max_digits=4, null=True)),
                ('combined', models.DecimalField(blank=True, decimal_places=2, help_text='Kết hợp(lít/100km)', max_digits=4, null=True)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_consumption', to='cars.carvariant')),
            ],
        ),
        migrations.CreateModel(
            name='InteriorSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steering_type', models.CharField(blank=True, help_text='Loại tay lái', max_length=30, null=True)),
                ('steering_material', models.CharField(blank=True, help_text='Chất liệu tay lái', max_length=30, null=True)),
                ('steering_adjust', models.CharField(blank=True, help_text='Điều chỉnh tay lái', max_length=30, null=True)),
                ('paddle_shifter', models.BooleanField(default=False, help_text='Lẫy chuyển số')),
                ('inner_mirror', models.CharField(blank=True, help_text='Gương chiếu hậu trong', max_length=50, null=True)),
                ('combination_metter', models.CharField(blank=True, help_text='Cụm đồng hồ', max_length=50, null=True)),
                ('sunroof', models.CharField(blank=True, help_text='Cửa sổ trời', max_length=30, null=True)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interior', to='cars.carvariant')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspension_font', models.CharField(blank=True, help_text='Hệ thống treo trước', max_length=30, null=True)),
                ('suspension_rear', models.CharField(blank=True, help_text='Hệ thống treo sau', max_length=30, null=True)),
                ('tire_size', models.CharField(blank=True, help_text='Kích thước lốp xe', max_length=30, null=True)),
                ('brake', models.CharField(blank=True, help_text='Phanh trước/sau(front/rear)', max_length=30, null=True)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='cars.carvariant')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 star'), (2, '2 star'), (3, '3 star'), (4, '4 star'), (5, '5 star')])),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('pros', models.TextField(blank=True, help_text='Ưu điểm')),
                ('cons', models.TextField(blank=True, help_text='Nhược điểm')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cars.carmodel')),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'verbose_name_plural': 'Đánh giá',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetySpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcs', models.BooleanField(default=False, help_text='Cảnh báo tiền va chạm(pre-collision warning)')),
                ('lda', models.BooleanField(default=False, help_text='Cảnh báo lệch làn đường(Lane departure alert')),
                ('lta', models.BooleanField(default=False, help_text='Hỗ trợ giữ làn đường(lane tracing assist')),
                ('drcc', models.BooleanField(default=False, help_text='Hệ thống điều khiển hành trình chủ động(Dynamic radar cruise control)')),
                ('ahb', models.BooleanField(default=False, help_text='Đèn chiếu xa tự động(Automatic high beam)')),
                ('parking_camera', models.CharField(blank=True, help_text='camera hỗ trợ đỗ xe', max_length=30, null=True)),
                ('bsm', models.BooleanField(default=False, help_text='Hế thống cảnh báo điểm mù(Blind spot monitor)')),
                ('rcta', models.BooleanField(default=False, help_text='Hệ thống hỗ trợ phương tiện cắt ngang phía sau(Rear cross traffic alert)')),
                ('abs', models.BooleanField(default=False, help_text='Hệ thống chống bó cứng phanh(Anti-lock braking system)')),
                ('ba', models.BooleanField(default=False, help_text='Hệ thống hỗ trợ lực phanh khẩn cấp(Brake assist)')),
                ('ebd', models.BooleanField(default=False, help_text='Hệ thống phân phối lực phanh điện từ(Electronic brake-force distribution)')),
                ('vsc', models.BooleanField(default=False, help_text='Hệ thống cân bằng điện tử(vehicle stability control')),
                ('trc', models.BooleanField(default=False, help_text='Hệ thống kiểm soát lực kéo(Traction control')),
                ('hac', models.BooleanField(default=False, help_text='Hệ thống hỗ trợ khởi hành ngang dốc(Hill-start assist control')),
                ('ebs', models.BooleanField(default=False, help_text='Hệ thống phanh khẩn cấp(Emergency brake signal)')),
                ('tpws', models.BooleanField(default=False, help_text='Hệ thống cảnh báo áp suất lốp(Tyre pressure warning system)')),
                ('sensor', models.PositiveSmallIntegerField(blank=True, help_text='Cảm biến hỗ trợ đổ xe', null=True)),
                ('airbag', models.PositiveSmallIntegerField(blank=True, help_text='Túi khí', null=True)),
                ('safety_rating', models.PositiveSmallIntegerField(blank=True, help_text='Sao NCAP', null=True)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety', to='cars.carvariant')),
            ],
        ),
        migrations.CreateModel(
            name='SeatSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_material', models.CharField(blank=True, help_text='Chất liệu bọc ghế', max_length=30, null=True)),
                ('driver_seat', models.CharField(blank=True, help_text='Điều chỉnh ghế lái', max_length=30, null=True)),
                ('front_passeger_seat', models.CharField(blank=True, help_text='Điều chỉnh ghế hành khách', max_length=30, null=True)),
                ('rear_seat', models.CharField(blank=True, help_text='Ghế sau', max_length=30, null=True)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seat', to='cars.carvariant')),
            ],
        ),
        migrations.AddIndex(
            model_name='carmodel',
            index=models.Index(fields=['car_slug'], name='cars_carmod_car_slu_544757_idx'),
        ),
        migrations.AddIndex(
            model_name='carmodel',
            index=models.Index(fields=['brand'], name='cars_carmod_brand_i_da877c_idx'),
        ),
        migrations.AddConstraint(
            model_name='carmodel',
            constraint=models.UniqueConstraint(fields=('brand', 'name'), name='unique_brand_name'),
        ),
        migrations.AddIndex(
            model_name='carvariant',
            index=models.Index(fields=['variant_slug'], name='cars_carvar_variant_21958d_idx'),
        ),
        migrations.AddIndex(
            model_name='carvariant',
            index=models.Index(fields=['fuel_type'], name='cars_carvar_fuel_ty_9d72e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='carvariant',
            constraint=models.UniqueConstraint(fields=('car_model', 'variant_name'), name='unique_car_variant'),
        ),
    ]
