# Generated by Django 6.0.3 on 2026-03-18 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('country_of_origin', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/logos/')),
                ('description', models.TextField(blank=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('model_year', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('body_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('pickup', 'Pickup Truck'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('minivan', 'Minivan')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Xăng'), ('diesel', 'Diesel'), ('electric', 'Điện'), ('hybrid', 'Hybrid'), ('plug_in_hybrid', 'Plug-in Hybrid')], max_length=20)),
                ('transmistion', models.CharField(choices=[('automatic', 'Tự động'), ('manual', 'Số sàn'), ('cvt', 'CVT')], max_length=20)),
                ('price_min', models.DecimalField(decimal_places=0, max_digits=15)),
                ('price_max', models.DecimalField(decimal_places=0, max_digits=15)),
                ('engine_capacity', models.DecimalField(blank=True, decimal_places=1, help_text='Dung tích xi lanh (lít)', max_digits=4, null=True)),
                ('horsepower', models.IntegerField(blank=True, help_text='Mã lực', null=True)),
                ('seating_capacity', models.IntegerField(default=5)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='cars/thumbnails/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.brand')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ['brand', 'name', '-model_year'],
            },
        ),
    ]
