# Generated by Django 6.0.3 on 2026-05-15 03:23

import cars.utils.upload_utils
import cars.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='carmodel',
            name='cars_carmod_car_slu_544757_idx',
        ),
        migrations.RemoveIndex(
            model_name='carvariant',
            name='cars_carvar_variant_21958d_idx',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='car_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='carvariant',
            old_name='variant_slug',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=cars.utils.upload_utils.UploadToPath('brand', 'logos', slug_field='slug'), validators=[cars.validators.validate_image_size, cars.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(upload_to=cars.utils.upload_utils.UploadToPath('cars', 'gallery', slug_field='car.slug'), validators=[cars.validators.validate_image_size, cars.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=cars.utils.upload_utils.UploadToPath('cars', 'thumbnail', slug_field='slug'), validators=[cars.validators.validate_image_size, cars.validators.validate_image_extension]),
        ),
        migrations.AddIndex(
            model_name='carmodel',
            index=models.Index(fields=['slug'], name='cars_carmod_slug_a252b7_idx'),
        ),
        migrations.AddIndex(
            model_name='carvariant',
            index=models.Index(fields=['slug'], name='cars_carvar_slug_58054e_idx'),
        ),
    ]
