# Generated by Django 6.0.3 on 2026-03-18 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='transmistion',
            new_name='transmission',
        ),
    ]
