# Generated by Django 6.0.3 on 2026-06-10 12:46

import cars.utils.upload_utils
import cars.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_slug_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=cars.utils.upload_utils.UploadToPath('variants', 'gallery', slug_field='variant.slug'), validators=[cars.validators.validate_image_extension, cars.validators.validate_image_size])),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Variant picture',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='carimage',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.carmodel'),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='lda',
            field=models.BooleanField(default=False, help_text='Cảnh báo lệch làn đường(Lane departure alert)'),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='lta',
            field=models.BooleanField(default=False, help_text='Hỗ trợ giữ làn đường(lane tracing assist)'),
        ),
        migrations.AddIndex(
            model_name='carvariant',
            index=models.Index(fields=['price_min'], name='cars_carvar_price_m_c10320_idx'),
        ),
        migrations.AddField(
            model_name='variantimage',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_images', to='cars.carvariant'),
        ),
    ]
