# Generated by Django 6.0.3 on 2026-03-19 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_brand_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/gallery/%Y/%m')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
            options={
                'verbose_name': 'Car picture',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CarSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(blank=True, max_length=100)),
                ('displacement', models.PositiveIntegerField(blank=True, help_text='cc', null=True)),
                ('max_power', models.PositiveIntegerField(blank=True, help_text='Hp', null=True)),
                ('max_torque', models.PositiveIntegerField(blank=True, help_text='Nm', null=True)),
                ('acceleration_0_100', models.DecimalField(blank=True, decimal_places=1, help_text='giây', max_digits=3, null=True)),
                ('top_speed', models.PositiveIntegerField(blank=True, help_text='km/h', null=True)),
                ('fuel_consumption', models.DecimalField(blank=True, decimal_places=1, help_text='L/100km', max_digits=3, null=True)),
                ('length', models.PositiveIntegerField(blank=True, help_text='mm', null=True)),
                ('width', models.PositiveIntegerField(blank=True, help_text='mm', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='mm', null=True)),
                ('wheelbase', models.PositiveIntegerField(blank=True, help_text='mm', null=True)),
                ('safety_rating', models.PositiveSmallIntegerField(blank=True, help_text='Sao NCAP', null=True)),
                ('num_airbags', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='cars.car')),
            ],
            options={
                'verbose_name': 'Specification',
            },
        ),
    ]
