# Generated by Django 6.0.3 on 2026-06-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_variantimage_alter_carimage_car_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='carvariant',
            name='unique_car_variant',
        ),
        migrations.RenameField(
            model_name='carvariant',
            old_name='variant_name',
            new_name='name',
        ),
        migrations.AddConstraint(
            model_name='carvariant',
            constraint=models.UniqueConstraint(fields=('car_model', 'name'), name='unique_car_variant'),
        ),
    ]
