# Generated by Django 6.0.3 on 2026-06-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_carvariant_unique_car_variant_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='carmodel',
            name='cars_carmod_brand_i_da877c_idx',
        ),
        migrations.RemoveIndex(
            model_name='carmodel',
            name='cars_carmod_slug_a252b7_idx',
        ),
        migrations.RemoveIndex(
            model_name='carvariant',
            name='cars_carvar_slug_58054e_idx',
        ),
        migrations.AddIndex(
            model_name='carmodel',
            index=models.Index(fields=['avg_rating'], name='cars_carmod_avg_rat_c329d6_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating', 'is_approved'], name='cars_review_rating_59ef92_idx'),
        ),
    ]
