# Generated by Django 6.0.3 on 2026-03-19 05:13

import cars.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carimage_carspecification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand/logos/', validators=[cars.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='car',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='cars/thumbnails/', validators=[cars.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(upload_to='cars/gallery/%Y/%m', validators=[cars.validators.validate_image_size]),
        ),
    ]
