# Generated by Django 6.0.3 on 2026-04-01 04:25

import cars.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_brand_logo_alter_car_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Automatically updated from reviews', max_digits=3),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand/logos/', validators=[cars.validators.validate_image_size, cars.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='car',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='cars/thumbnails/', validators=[cars.validators.validate_image_size, cars.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(upload_to='cars/gallery/%Y/%m', validators=[cars.validators.validate_image_size, cars.validators.validate_image_extension]),
        ),
    ]
