# Generated by Django 6.0.6 on 2026-06-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_carmodel_cars_carmod_brand_i_da877c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='air_conditioner',
            field=models.CharField(blank=True, default='', help_text='Hệ thống điều hòa', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='display',
            field=models.CharField(blank=True, default='', help_text='Màn hình giải trí', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='number_of_speaker',
            field=models.CharField(blank=True, default='', help_text='Số loa', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='power_window',
            field=models.CharField(blank=True, default='', help_text='Cửa sổ điều chỉnh điện', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='smart_connect',
            field=models.CharField(blank=True, default='', help_text='Kết nối không dây', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enginespecification',
            name='drive_train',
            field=models.CharField(blank=True, default='', help_text='Hệ số truyền động', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='foglamp',
            field=models.CharField(blank=True, default='', help_text='Đèn sương mù', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='headlamp',
            field=models.CharField(blank=True, default='', help_text='Đèn chiếu sáng trước', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='rearlamp',
            field=models.CharField(blank=True, default='', help_text='Đèn hậu', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='wiper_front',
            field=models.CharField(blank=True, default='', help_text='Gạt mưa trước', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='wiper_rear',
            field=models.CharField(blank=True, default='', help_text='Gạt mưa sau', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interiorspecification',
            name='combination_metter',
            field=models.CharField(blank=True, default='', help_text='Cụm đồng hồ', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interiorspecification',
            name='inner_mirror',
            field=models.CharField(blank=True, default='', help_text='Gương chiếu hậu trong', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interiorspecification',
            name='steering_adjust',
            field=models.CharField(blank=True, default='', help_text='Điều chỉnh tay lái', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interiorspecification',
            name='steering_material',
            field=models.CharField(blank=True, default='', help_text='Chất liệu tay lái', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interiorspecification',
            name='steering_type',
            field=models.CharField(blank=True, default='', help_text='Loại tay lái', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interiorspecification',
            name='sunroof',
            field=models.CharField(blank=True, default='', help_text='Cửa sổ trời', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performancespecification',
            name='brake',
            field=models.CharField(blank=True, default='', help_text='Phanh trước/sau(front/rear)', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performancespecification',
            name='suspension_font',
            field=models.CharField(blank=True, default='', help_text='Hệ thống treo trước', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performancespecification',
            name='suspension_rear',
            field=models.CharField(blank=True, default='', help_text='Hệ thống treo sau', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performancespecification',
            name='tire_size',
            field=models.CharField(blank=True, default='', help_text='Kích thước lốp xe', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='parking_camera',
            field=models.CharField(blank=True, default='', help_text='camera hỗ trợ đỗ xe', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seatspecification',
            name='driver_seat',
            field=models.CharField(blank=True, default='', help_text='Điều chỉnh ghế lái', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seatspecification',
            name='front_passeger_seat',
            field=models.CharField(blank=True, default='', help_text='Điều chỉnh ghế hành khách', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seatspecification',
            name='rear_seat',
            field=models.CharField(blank=True, default='', help_text='Ghế sau', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seatspecification',
            name='seat_material',
            field=models.CharField(blank=True, default='', help_text='Chất liệu bọc ghế', max_length=30),
            preserve_default=False,
        ),
    ]
