# Generated by Django 6.0.3 on 2026-04-01 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_avg_rating_alter_brand_logo_alter_car_thumbnail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 star'), (2, '2 star'), (3, '3 star'), (4, '4 star'), (5, '5 star')])),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('pros', models.TextField(blank=True, help_text='Ưu điểm')),
                ('cons', models.TextField(blank=True, help_text='Nhược điểm')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cars.car')),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'ordering': ['-created_at'],
            },
        ),
    ]
