# Generated by Django 6.0.6 on 2026-07-14 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_brand_description_alter_carmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodytype',
            options={'verbose_name_plural': 'Body Types'},
        ),
        migrations.AlterModelOptions(
            name='carclass',
            options={'verbose_name_plural': 'Car Classes'},
        ),
    ]
