# Generated by Django 6.0.6 on 2026-07-31 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_bodytype_options_alter_carclass_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='carvariant',
            name='fuel_system',
            field=models.CharField(blank=True, help_text='Hệ thống nhiên liệu', max_length=100),
        ),
        migrations.AddField(
            model_name='carvariant',
            name='origin_country',
            field=models.CharField(blank=True, help_text='Xuất xứ', max_length=100),
        ),
        migrations.AddField(
            model_name='comfortspecification',
            name='bluetooth',
            field=models.BooleanField(default=False, help_text='Kết nối bluetooth'),
        ),
        migrations.AddField(
            model_name='comfortspecification',
            name='control_rear_seat',
            field=models.BooleanField(default=False, help_text='Chức năng điều khiển từ hàng ghế sau'),
        ),
        migrations.AddField(
            model_name='comfortspecification',
            name='cooler_box',
            field=models.BooleanField(default=False, help_text='Hộp làm mát'),
        ),
        migrations.AddField(
            model_name='comfortspecification',
            name='display_info_windsheld',
            field=models.BooleanField(default=False, help_text='Hiển thị thông tin trên kính lái'),
        ),
        migrations.AddField(
            model_name='comfortspecification',
            name='hands_free_calling',
            field=models.BooleanField(default=False, help_text='Hệ thống đàm thoại rảnh tay'),
        ),
        migrations.AddField(
            model_name='comfortspecification',
            name='power_door',
            field=models.BooleanField(default=False, help_text='Khóa cửa điện'),
        ),
        migrations.AddField(
            model_name='comfortspecification',
            name='rear_door_sunshade',
            field=models.CharField(blank=True, help_text='Rèm che nắng cửa sau', max_length=100),
        ),
        migrations.AddField(
            model_name='comfortspecification',
            name='rear_window_sunshade',
            field=models.CharField(blank=True, help_text='Rèm che nắng phía sau', max_length=100),
        ),
        migrations.AddField(
            model_name='comfortspecification',
            name='remote_door',
            field=models.BooleanField(default=False, help_text='Chức năng khóa cửa từ xa'),
        ),
        migrations.AddField(
            model_name='comfortspecification',
            name='smart_mobile_connect',
            field=models.BooleanField(default=False, help_text='Kết nối điện thoại thông minh không dây'),
        ),
        migrations.AddField(
            model_name='comfortspecification',
            name='usb_connect_front',
            field=models.BooleanField(default=False, help_text='Cổng kết nối usb'),
        ),
        migrations.AddField(
            model_name='comfortspecification',
            name='usb_connect_rear',
            field=models.BooleanField(default=False, help_text='Cổng kết nối phía sau'),
        ),
        migrations.AddField(
            model_name='comfortspecification',
            name='voice_control',
            field=models.BooleanField(default=False, help_text='Hệ thống điều khiển bằng giọng nói'),
        ),
        migrations.AddField(
            model_name='comfortspecification',
            name='wireless_charging',
            field=models.BooleanField(default=False, help_text='Sạc không dây'),
        ),
        migrations.AddField(
            model_name='dimensionspecification',
            name='full_loaded_weight',
            field=models.PositiveIntegerField(blank=True, help_text='Trọng lượng toàn tải (kg)', null=True),
        ),
        migrations.AddField(
            model_name='dimensionspecification',
            name='turning_radius',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Bán kính vòng quay tối thiểu (m)', null=True),
        ),
        migrations.AddField(
            model_name='dimensionspecification',
            name='unloaded_weight',
            field=models.PositiveIntegerField(blank=True, help_text='Trọng lượng không tải (kg)', null=True),
        ),
        migrations.AddField(
            model_name='enginespecification',
            name='cylinder_arrangement',
            field=models.CharField(blank=True, help_text='Bố trí xy lanh', max_length=50),
        ),
        migrations.AddField(
            model_name='enginespecification',
            name='drive_mode',
            field=models.CharField(blank=True, help_text='Các chế độ lái', max_length=100),
        ),
        migrations.AddField(
            model_name='enginespecification',
            name='electric_motor_mp',
            field=models.CharField(blank=True, help_text='Công suất tối đa KW (động cơ điện)', max_length=50),
        ),
        migrations.AddField(
            model_name='enginespecification',
            name='electric_motor_mt',
            field=models.CharField(blank=True, help_text='Momen xoắn tối đa Nm', max_length=50),
        ),
        migrations.AddField(
            model_name='enginespecification',
            name='hybrid_batteries',
            field=models.CharField(blank=True, help_text='Ắc quy hybrid', max_length=50),
        ),
        migrations.AddField(
            model_name='enginespecification',
            name='number_of_cylinders',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Số xy lanh', null=True),
        ),
        migrations.AddField(
            model_name='enginespecification',
            name='variable_valve_system',
            field=models.CharField(blank=True, help_text='Hệ thống van biến thiên', max_length=50),
        ),
        migrations.AddField(
            model_name='exteriorspecification',
            name='antenna',
            field=models.CharField(blank=True, help_text='Ăng ten', max_length=50),
        ),
        migrations.AddField(
            model_name='exteriorspecification',
            name='brake_light',
            field=models.CharField(blank=True, help_text='Đèn phanh', max_length=30),
        ),
        migrations.AddField(
            model_name='exteriorspecification',
            name='bumper_bar_front',
            field=models.BooleanField(default=False, help_text='Thanh cản trước'),
        ),
        migrations.AddField(
            model_name='exteriorspecification',
            name='bumper_bar_rear',
            field=models.BooleanField(default=False, help_text='Thanh cản sau'),
        ),
        migrations.AddField(
            model_name='exteriorspecification',
            name='foglamp_front',
            field=models.CharField(blank=True, help_text='Đèn sương mù trước', max_length=30),
        ),
        migrations.AddField(
            model_name='exteriorspecification',
            name='foglamp_rear',
            field=models.CharField(blank=True, help_text='Đèn sương mù sau', max_length=30),
        ),
        migrations.AddField(
            model_name='exteriorspecification',
            name='high_beam_headlight',
            field=models.CharField(blank=True, help_text='Đèn chiếu xa', max_length=30),
        ),
        migrations.AddField(
            model_name='exteriorspecification',
            name='itsl',
            field=models.BooleanField(default=False, help_text='Tích hợp đèn báo rẽ'),
        ),
        migrations.AddField(
            model_name='exteriorspecification',
            name='iwl',
            field=models.BooleanField(default=False, help_text='Tích hợp đèn chào mừng'),
        ),
        migrations.AddField(
            model_name='exteriorspecification',
            name='low_beam_headlight',
            field=models.CharField(blank=True, help_text='Đèn chiếu gần trước', max_length=30),
        ),
        migrations.AddField(
            model_name='exteriorspecification',
            name='mirror_color',
            field=models.CharField(blank=True, help_text='Màu gương', max_length=50),
        ),
        migrations.AddField(
            model_name='exteriorspecification',
            name='mirror_memory',
            field=models.BooleanField(default=False, help_text='Nhớ vị trí gương'),
        ),
        migrations.AddField(
            model_name='exteriorspecification',
            name='mudguard',
            field=models.CharField(blank=True, help_text='Chắn bùn', max_length=40),
        ),
        migrations.AddField(
            model_name='exteriorspecification',
            name='nlm',
            field=models.BooleanField(default=False, help_text='Chế độ đèn chờ dẫn đường (Navigation light mode)'),
        ),
        migrations.AddField(
            model_name='exteriorspecification',
            name='outside_handle',
            field=models.CharField(blank=True, help_text='Tay nắm cửa ngoài xe', max_length=50),
        ),
        migrations.AddField(
            model_name='exteriorspecification',
            name='pabs',
            field=models.CharField(blank=True, help_text='Hệ thống cân bằng góc chiếu (Projection angle balancing system)', max_length=30),
        ),
        migrations.AddField(
            model_name='exteriorspecification',
            name='position_light',
            field=models.CharField(blank=True, help_text='Đèn vị trí', max_length=30),
        ),
        migrations.AddField(
            model_name='exteriorspecification',
            name='reverse_light',
            field=models.CharField(blank=True, help_text='Đèn lùi', max_length=30),
        ),
        migrations.AddField(
            model_name='exteriorspecification',
            name='self_adjust_reverse',
            field=models.BooleanField(default=False, help_text='Tự điều chỉnh khi lùi'),
        ),
        migrations.AddField(
            model_name='exteriorspecification',
            name='support_bar',
            field=models.BooleanField(default=False, help_text='Thanh đỡ nóc xe'),
        ),
        migrations.AddField(
            model_name='exteriorspecification',
            name='third_brake_lamp',
            field=models.CharField(blank=True, help_text='Đèn phanh trên cao, đèn phanh thứ 3', max_length=30),
        ),
        migrations.AddField(
            model_name='fuelconsumptionspecification',
            name='emission_standards',
            field=models.CharField(blank=True, help_text='Tiêu chuẩn khí thải', max_length=50),
        ),
        migrations.AddField(
            model_name='interiorspecification',
            name='eco_signal',
            field=models.BooleanField(default=False, help_text='Đèn báo chế độ Eco'),
        ),
        migrations.AddField(
            model_name='interiorspecification',
            name='fcif',
            field=models.BooleanField(default=False, help_text='Chức năng báo tiêu thụ nhiên liệu'),
        ),
        migrations.AddField(
            model_name='interiorspecification',
            name='gear_position',
            field=models.BooleanField(default=False, help_text='Chức năng báo vị trí cần số'),
        ),
        migrations.AddField(
            model_name='interiorspecification',
            name='hybrid_signal',
            field=models.BooleanField(default=False, help_text='Đèn báo chế độ Hybrid'),
        ),
        migrations.AddField(
            model_name='interiorspecification',
            name='icb',
            field=models.CharField(blank=True, help_text='Nút bấm điều khiển tích hơp (Integrated control buttons)', max_length=200),
        ),
        migrations.AddField(
            model_name='interiorspecification',
            name='inside_handle_door',
            field=models.CharField(blank=True, help_text='Tay nắm cửa trong xe', max_length=50),
        ),
        migrations.AddField(
            model_name='interiorspecification',
            name='metter_type',
            field=models.CharField(blank=True, help_text='Loại đồng hồ', max_length=50),
        ),
        migrations.AddField(
            model_name='interiorspecification',
            name='multi_info_display',
            field=models.CharField(blank=True, help_text='Màn hình hiển thị đa thông tin', max_length=100),
        ),
        migrations.AddField(
            model_name='interiorspecification',
            name='steering_memory',
            field=models.BooleanField(default=False, help_text='Nhớ vị trí tay lái'),
        ),
        migrations.AddField(
            model_name='performancespecification',
            name='brake_front',
            field=models.CharField(blank=True, help_text='Phanh trước', max_length=50),
        ),
        migrations.AddField(
            model_name='performancespecification',
            name='brake_rear',
            field=models.CharField(blank=True, help_text='Phanh sau', max_length=50),
        ),
        migrations.AddField(
            model_name='performancespecification',
            name='power_steering',
            field=models.CharField(blank=True, help_text='Trợ lực tay lái', max_length=100),
        ),
        migrations.AddField(
            model_name='performancespecification',
            name='rim_type',
            field=models.CharField(blank=True, help_text='Loại vành', max_length=50),
        ),
        migrations.AddField(
            model_name='performancespecification',
            name='spare_tire',
            field=models.CharField(blank=True, help_text='Lốp dự phòng', max_length=50),
        ),
        migrations.AddField(
            model_name='safetyspecification',
            name='camera_360',
            field=models.BooleanField(default=False, help_text='Camera 360'),
        ),
        migrations.AddField(
            model_name='safetyspecification',
            name='child_safety_lock',
            field=models.CharField(blank=True, help_text='Khóa an toàn trẻ em', max_length=50),
        ),
        migrations.AddField(
            model_name='safetyspecification',
            name='curtain_airbag',
            field=models.CharField(blank=True, help_text='Túi khí rèm', max_length=30),
        ),
        migrations.AddField(
            model_name='safetyspecification',
            name='driver_knee_airbag',
            field=models.CharField(blank=True, help_text='Túi khí đầu gối người lái', max_length=30),
        ),
        migrations.AddField(
            model_name='safetyspecification',
            name='exit_safety',
            field=models.BooleanField(default=False, help_text='Hệ thống hỗ trợ ra khỏi xe an toàn'),
        ),
        migrations.AddField(
            model_name='safetyspecification',
            name='font_airbag',
            field=models.CharField(blank=True, help_text='Túi khí phía trước', max_length=30),
        ),
        migrations.AddField(
            model_name='safetyspecification',
            name='front_side_airbag',
            field=models.CharField(blank=True, help_text='Túi khí bên hông phía trước', max_length=30),
        ),
        migrations.AddField(
            model_name='safetyspecification',
            name='parking_brake',
            field=models.BooleanField(default=False, help_text='Phanh hỗ trợ đổ xe'),
        ),
        migrations.AddField(
            model_name='safetyspecification',
            name='reverse_camera',
            field=models.BooleanField(default=False, help_text='Camera lùi'),
        ),
        migrations.AddField(
            model_name='safetyspecification',
            name='seat_belt',
            field=models.CharField(blank=True, help_text='Dây đai an toàn', max_length=50),
        ),
        migrations.AddField(
            model_name='safetyspecification',
            name='secure_door',
            field=models.BooleanField(default=False, help_text='Khóa cửa an toàn'),
        ),
        migrations.AddField(
            model_name='safetyspecification',
            name='sensor_front',
            field=models.BooleanField(default=False, help_text='Cảm biến hỗ trợ đổ xe trước'),
        ),
        migrations.AddField(
            model_name='safetyspecification',
            name='sensor_front_corner',
            field=models.BooleanField(default=False, help_text='Cảm biến hỗ trợ đổ xe góc trước'),
        ),
        migrations.AddField(
            model_name='safetyspecification',
            name='sensor_rear',
            field=models.BooleanField(default=False, help_text='Cảm biến hỗ trợ đổ xe phía sau'),
        ),
        migrations.AddField(
            model_name='safetyspecification',
            name='sensor_rear_corner',
            field=models.BooleanField(default=False, help_text='Cảm biến hỗ trợ đổ xe góc sau'),
        ),
        migrations.AddField(
            model_name='safetyspecification',
            name='tpms',
            field=models.BooleanField(default=False, help_text='Hệ thống theo dõi áp suất lốp'),
        ),
        migrations.AddField(
            model_name='seatspecification',
            name='front_seat_type',
            field=models.CharField(blank=True, help_text='Loại ghế trước', max_length=50),
        ),
        migrations.AddField(
            model_name='seatspecification',
            name='rear_seat_armset',
            field=models.CharField(blank=True, help_text='Tựa tay hàng ghế sau', max_length=50),
        ),
        migrations.AddField(
            model_name='seatspecification',
            name='seat_memory',
            field=models.CharField(blank=True, help_text='Bộ nhớ vị trí ghế', max_length=50),
        ),
        migrations.AddField(
            model_name='seatspecification',
            name='second_seat',
            field=models.CharField(blank=True, help_text='Hàng ghế thứ hai', max_length=100),
        ),
        migrations.AddField(
            model_name='seatspecification',
            name='third_seat',
            field=models.CharField(blank=True, help_text='Hàng ghế thứ ba', max_length=100),
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='air_conditioner',
            field=models.CharField(blank=True, help_text='Hệ thống điều hòa', max_length=100),
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='cruise_control',
            field=models.BooleanField(default=False, help_text='Hệ thống điều khiển hành trình (ga tự động)'),
        ),
        migrations.AlterField(
            model_name='enginespecification',
            name='engine_type',
            field=models.CharField(blank=True, help_text='Loại động cơ', max_length=100),
        ),
        migrations.AlterField(
            model_name='enginespecification',
            name='max_power',
            field=models.CharField(blank=True, default='', help_text='Công suất tối đa(Hp)', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enginespecification',
            name='max_torque',
            field=models.CharField(blank=True, default='', help_text='Momen xoắn tối đa(Nm)', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enginespecification',
            name='transmission',
            field=models.CharField(choices=[('automatic', 'Tự động'), ('manual', 'Số sàn'), ('cvt', 'CVT')], help_text='Hộp số', max_length=40),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='auto_light_control',
            field=models.BooleanField(default=False, help_text='Tự động bật tắt đèn'),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='daytime_running_light',
            field=models.BooleanField(default=False, help_text='Đèn chiếu sáng ban ngày'),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='power_adjust_mirror',
            field=models.BooleanField(default=False, help_text='Điều chỉnh bằng điện'),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='power_fold_mirror',
            field=models.BooleanField(default=False, help_text='Gập điện'),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='turn_signal_lamp',
            field=models.CharField(blank=True, help_text='Tích hợp đèn báo rẽ', max_length=30),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='airbag',
            field=models.CharField(blank=True, default='', help_text='Túi khí', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='ebs',
            field=models.BooleanField(default=False, help_text='Hệ thống đèn báo phanh khẩn cấp(Emergency brake signal)'),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='sensor',
            field=models.CharField(blank=True, default='', help_text='Cảm biến hỗ trợ đổ xe', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SecureSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_system', models.BooleanField(default=False, help_text='Hệ thống báo động (An ninh)')),
                ('eis', models.BooleanField(default=False, help_text='Hệ thống mã hóa khóa động cơ')),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secure', to='cars.carvariant')),
            ],
        ),
    ]
