# Generated by Django 6.0.3 on 2026-04-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đánh giá', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 star'), (2, '2 star'), (3, '3 star'), (4, '4 star'), (5, '5 star')]),
        ),
    ]
