# Generated by Django 6.0.6 on 2026-08-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_carvariant_fuel_system_carvariant_origin_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comfortspecification',
            name='display',
            field=models.CharField(blank=True, help_text='Màn hình giải trí', max_length=50),
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='number_of_speaker',
            field=models.CharField(blank=True, help_text='Số loa', max_length=50),
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='power_window',
            field=models.CharField(blank=True, help_text='Cửa sổ điều chỉnh điện', max_length=50),
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='smart_connect',
            field=models.CharField(blank=True, help_text='Kết nối không dây', max_length=50),
        ),
        migrations.AlterField(
            model_name='enginespecification',
            name='displacement',
            field=models.CharField(blank=True, default='', help_text='Dung tích xi lanh(cc)', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='pabs',
            field=models.CharField(blank=True, help_text='Hệ thống cân bằng góc chiếu (Projection angle balancing system)', max_length=50),
        ),
        migrations.AlterField(
            model_name='interiorspecification',
            name='steering_adjust',
            field=models.CharField(blank=True, help_text='Điều chỉnh tay lái', max_length=50),
        ),
        migrations.AlterField(
            model_name='interiorspecification',
            name='steering_material',
            field=models.CharField(blank=True, help_text='Chất liệu tay lái', max_length=50),
        ),
        migrations.AlterField(
            model_name='interiorspecification',
            name='steering_type',
            field=models.CharField(blank=True, help_text='Loại tay lái', max_length=50),
        ),
        migrations.AlterField(
            model_name='interiorspecification',
            name='sunroof',
            field=models.CharField(blank=True, help_text='Cửa sổ trời', max_length=50),
        ),
        migrations.AlterField(
            model_name='performancespecification',
            name='brake',
            field=models.CharField(blank=True, help_text='Phanh trước/sau(front/rear)', max_length=50),
        ),
        migrations.AlterField(
            model_name='performancespecification',
            name='suspension_font',
            field=models.CharField(blank=True, help_text='Hệ thống treo trước', max_length=50),
        ),
        migrations.AlterField(
            model_name='performancespecification',
            name='suspension_rear',
            field=models.CharField(blank=True, help_text='Hệ thống treo sau', max_length=50),
        ),
        migrations.AlterField(
            model_name='performancespecification',
            name='tire_size',
            field=models.CharField(blank=True, help_text='Kích thước lốp xe', max_length=50),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='curtain_airbag',
            field=models.CharField(blank=True, help_text='Túi khí rèm', max_length=50),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='driver_knee_airbag',
            field=models.CharField(blank=True, help_text='Túi khí đầu gối người lái', max_length=50),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='font_airbag',
            field=models.CharField(blank=True, help_text='Túi khí phía trước', max_length=50),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='front_side_airbag',
            field=models.CharField(blank=True, help_text='Túi khí bên hông phía trước', max_length=50),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='parking_camera',
            field=models.CharField(blank=True, help_text='camera hỗ trợ đỗ xe', max_length=50),
        ),
        migrations.AlterField(
            model_name='seatspecification',
            name='driver_seat',
            field=models.CharField(blank=True, help_text='Điều chỉnh ghế lái', max_length=50),
        ),
        migrations.AlterField(
            model_name='seatspecification',
            name='front_passeger_seat',
            field=models.CharField(blank=True, help_text='Điều chỉnh ghế hành khách', max_length=50),
        ),
        migrations.AlterField(
            model_name='seatspecification',
            name='rear_seat',
            field=models.CharField(blank=True, help_text='Ghế sau', max_length=50),
        ),
        migrations.AlterField(
            model_name='seatspecification',
            name='seat_material',
            field=models.CharField(blank=True, help_text='Chất liệu bọc ghế', max_length=50),
        ),
    ]
