# Generated by Django 6.0.6 on 2026-08-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_comfortspecification_display_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimensionspecification',
            name='fuel_tank_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dung tích bình nhiên liệu(lít)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='dimensionspecification',
            name='turning_radius',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bán kính vòng quay tối thiểu (m)', max_digits=4, null=True),
        ),
    ]
