# Generated by Django 6.0.6 on 2026-08-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_dimensionspecification_fuel_tank_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginespecification',
            name='drive_train',
            field=models.CharField(blank=True, help_text='Hệ số truyền động', max_length=50),
        ),
        migrations.AlterField(
            model_name='enginespecification',
            name='number_of_cylinders',
            field=models.CharField(blank=True, default='', help_text='Số xy lanh', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='brake_light',
            field=models.CharField(blank=True, help_text='Đèn phanh', max_length=50),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='foglamp',
            field=models.CharField(blank=True, help_text='Đèn sương mù', max_length=50),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='foglamp_front',
            field=models.CharField(blank=True, help_text='Đèn sương mù trước', max_length=50),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='foglamp_rear',
            field=models.CharField(blank=True, help_text='Đèn sương mù sau', max_length=50),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='headlamp',
            field=models.CharField(blank=True, help_text='Đèn chiếu sáng trước', max_length=50),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='high_beam_headlight',
            field=models.CharField(blank=True, help_text='Đèn chiếu xa', max_length=50),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='low_beam_headlight',
            field=models.CharField(blank=True, help_text='Đèn chiếu gần trước', max_length=50),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='position_light',
            field=models.CharField(blank=True, help_text='Đèn vị trí', max_length=50),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='rearlamp',
            field=models.CharField(blank=True, help_text='Đèn hậu', max_length=50),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='reverse_light',
            field=models.CharField(blank=True, help_text='Đèn lùi', max_length=50),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='third_brake_lamp',
            field=models.CharField(blank=True, help_text='Đèn phanh trên cao, đèn phanh thứ 3', max_length=50),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='turn_signal_lamp',
            field=models.CharField(blank=True, help_text='Tích hợp đèn báo rẽ', max_length=50),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='wiper_front',
            field=models.CharField(blank=True, help_text='Gạt mưa trước', max_length=50),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='wiper_rear',
            field=models.CharField(blank=True, help_text='Gạt mưa sau', max_length=50),
        ),
    ]
