# Generated by Django 6.0.6 on 2026-08-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_alter_enginespecification_drive_train_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comfortspecification',
            options={'verbose_name': 'Tiện Lợi'},
        ),
        migrations.AlterModelOptions(
            name='dimensionspecification',
            options={'verbose_name': 'Tổng Thể'},
        ),
        migrations.AlterModelOptions(
            name='enginespecification',
            options={'verbose_name': 'Động Cơ'},
        ),
        migrations.AlterModelOptions(
            name='exteriorspecification',
            options={'verbose_name': 'Ngoại Thất'},
        ),
        migrations.AlterModelOptions(
            name='fuelconsumptionspecification',
            options={'verbose_name': 'Nhiên Liệu'},
        ),
        migrations.AlterModelOptions(
            name='interiorspecification',
            options={'verbose_name': 'Nội Thất'},
        ),
        migrations.AlterModelOptions(
            name='performancespecification',
            options={'verbose_name': 'Vận Hành'},
        ),
        migrations.AlterModelOptions(
            name='safetyspecification',
            options={'verbose_name': 'An Toàn'},
        ),
        migrations.AlterModelOptions(
            name='seatspecification',
            options={'verbose_name': 'Ghế Ngồi'},
        ),
        migrations.AlterModelOptions(
            name='securespecification',
            options={'verbose_name': 'An Ninh'},
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='nlm',
            field=models.BooleanField(default=False, help_text='Chế độ đèn chờ dẫn đường'),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='pabs',
            field=models.CharField(blank=True, help_text='Hệ thống cân bằng góc chiếu ', max_length=50),
        ),
        migrations.AlterField(
            model_name='fuelconsumptionspecification',
            name='combined',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mức tiêu thụ kết hợp(lít/100km)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='fuelconsumptionspecification',
            name='extra_urban',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mức tiêu thụ ngoài đô thị(lít/100km)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='fuelconsumptionspecification',
            name='urban',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mức tiêu thụ trong đô thị(lit/100km)', max_digits=4, null=True),
        ),
    ]
