# Generated by Django 6.0.6 on 2026-08-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_alter_comfortspecification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimensionspecification',
            name='overall_dimensions',
            field=models.CharField(blank=True, help_text='Kích thước tổng thể (DxRxC)', max_length=100),
        ),
        migrations.AddField(
            model_name='enginespecification',
            name='compression_ratio',
            field=models.CharField(blank=True, help_text='Tỉ số nén', max_length=50),
        ),
        migrations.AddField(
            model_name='exteriorspecification',
            name='bumper_bar',
            field=models.CharField(blank=True, help_text='Thanh cản trước và sau', max_length=100),
        ),
        migrations.AddField(
            model_name='exteriorspecification',
            name='cornering_light',
            field=models.BooleanField(default=False, help_text='Đèn chiếu góc'),
        ),
        migrations.AddField(
            model_name='exteriorspecification',
            name='hls',
            field=models.CharField(blank=True, help_text='Hệ thống cân bằng góc chiếu', max_length=50),
        ),
        migrations.AddField(
            model_name='exteriorspecification',
            name='light_on_reminder',
            field=models.BooleanField(default=False, help_text='Hệ thống nhắc nhở đèn sáng'),
        ),
        migrations.AddField(
            model_name='interiorspecification',
            name='power_steering',
            field=models.CharField(blank=True, help_text='Trợ lực tay lái', max_length=100),
        ),
        migrations.AddField(
            model_name='performancespecification',
            name='suspension',
            field=models.CharField(blank=True, help_text='Hệ thống treo', max_length=100),
        ),
        migrations.AlterField(
            model_name='enginespecification',
            name='drive_train',
            field=models.CharField(blank=True, help_text='Hệ thống truyền động', max_length=50),
        ),
        migrations.AlterField(
            model_name='performancespecification',
            name='brake',
            field=models.CharField(blank=True, help_text='Hệ thống phanh trước/sau(front/rear)', max_length=50),
        ),
        migrations.AlterField(
            model_name='performancespecification',
            name='brake_front',
            field=models.CharField(blank=True, help_text='Hệ thống phanh trước', max_length=50),
        ),
        migrations.AlterField(
            model_name='performancespecification',
            name='brake_rear',
            field=models.CharField(blank=True, help_text='Hệ thống phanh sau', max_length=50),
        ),
    ]
