# Generated by Django 6.0.6 on 2026-08-14 02:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_dimensionspecification_overall_dimensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='carvariant',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='carvariant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exteriorspecification',
            name='mirror',
            field=models.CharField(blank=True, default='', help_text='Gương chiếu hậu ngoài', max_length=150),
        ),
        migrations.AddField(
            model_name='seatspecification',
            name='seat_type',
            field=models.CharField(blank=True, default='', help_text='Loại ghế', max_length=150),
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='display',
            field=models.CharField(blank=True, help_text='Màn hình giải trí', max_length=100),
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='number_of_speaker',
            field=models.CharField(blank=True, help_text='Số loa', max_length=100),
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='power_window',
            field=models.CharField(blank=True, help_text='Cửa sổ điều chỉnh điện', max_length=100),
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='smart_connect',
            field=models.CharField(blank=True, help_text='Kết nối không dây', max_length=100),
        ),
        migrations.AlterField(
            model_name='dimensionspecification',
            name='fuel_tank_capacity',
            field=models.CharField(blank=True, default='', help_text='Dung tích bình nhiên liệu(lít)', max_length=150),
        ),
        migrations.AlterField(
            model_name='dimensionspecification',
            name='full_loaded_weight',
            field=models.CharField(blank=True, default='', help_text='Trọng lượng toàn tải (kg)', max_length=150),
        ),
        migrations.AlterField(
            model_name='dimensionspecification',
            name='ground_clearance',
            field=models.CharField(blank=True, default='', help_text='Khoảng sáng gầm xe(mm)', max_length=150),
        ),
        migrations.AlterField(
            model_name='dimensionspecification',
            name='seating_capacity',
            field=models.CharField(blank=True, default='', help_text='Số chỗ ngồi', max_length=150),
        ),
        migrations.AlterField(
            model_name='dimensionspecification',
            name='turning_radius',
            field=models.CharField(blank=True, default='', help_text='Bán kính vòng quay tối thiểu (m)'),
        ),
        migrations.AlterField(
            model_name='dimensionspecification',
            name='unloaded_weight',
            field=models.CharField(blank=True, default='', help_text='Trọng lượng không tải (kg)', max_length=150),
        ),
        migrations.AlterField(
            model_name='dimensionspecification',
            name='wheelbase',
            field=models.CharField(blank=True, default='', help_text='Chiều dài cơ sở(mm)'),
        ),
        migrations.AlterField(
            model_name='enginespecification',
            name='compression_ratio',
            field=models.CharField(blank=True, help_text='Tỉ số nén', max_length=150),
        ),
        migrations.AlterField(
            model_name='enginespecification',
            name='cylinder_arrangement',
            field=models.CharField(blank=True, help_text='Bố trí xy lanh', max_length=150),
        ),
        migrations.AlterField(
            model_name='enginespecification',
            name='displacement',
            field=models.CharField(blank=True, help_text='Dung tích xi lanh(cc)', max_length=150),
        ),
        migrations.AlterField(
            model_name='enginespecification',
            name='drive_train',
            field=models.CharField(blank=True, help_text='Hệ thống truyền động', max_length=150),
        ),
        migrations.AlterField(
            model_name='enginespecification',
            name='electric_motor_mp',
            field=models.CharField(blank=True, help_text='Công suất tối đa KW (động cơ điện)', max_length=150),
        ),
        migrations.AlterField(
            model_name='enginespecification',
            name='electric_motor_mt',
            field=models.CharField(blank=True, help_text='Momen xoắn tối đa Nm', max_length=150),
        ),
        migrations.AlterField(
            model_name='enginespecification',
            name='hybrid_batteries',
            field=models.CharField(blank=True, help_text='Ắc quy hybrid', max_length=150),
        ),
        migrations.AlterField(
            model_name='enginespecification',
            name='transmission',
            field=models.CharField(choices=[('automatic', 'Tự động'), ('manual', 'Số sàn'), ('cvt', 'CVT')], help_text='Hộp số', max_length=150),
        ),
        migrations.AlterField(
            model_name='enginespecification',
            name='variable_valve_system',
            field=models.CharField(blank=True, help_text='Hệ thống van biến thiên', max_length=150),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='antenna',
            field=models.CharField(blank=True, help_text='Ăng ten', max_length=150),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='brake_light',
            field=models.CharField(blank=True, help_text='Đèn phanh', max_length=150),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='foglamp',
            field=models.CharField(blank=True, help_text='Đèn sương mù', max_length=150),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='foglamp_front',
            field=models.CharField(blank=True, help_text='Đèn sương mù trước', max_length=150),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='foglamp_rear',
            field=models.CharField(blank=True, help_text='Đèn sương mù sau', max_length=150),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='headlamp',
            field=models.CharField(blank=True, help_text='Đèn chiếu sáng trước', max_length=150),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='high_beam_headlight',
            field=models.CharField(blank=True, help_text='Đèn chiếu xa', max_length=150),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='hls',
            field=models.CharField(blank=True, help_text='Hệ thống cân bằng góc chiếu', max_length=150),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='low_beam_headlight',
            field=models.CharField(blank=True, help_text='Đèn chiếu gần trước', max_length=150),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='mirror_color',
            field=models.CharField(blank=True, help_text='Màu gương', max_length=150),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='mudguard',
            field=models.CharField(blank=True, help_text='Chắn bùn', max_length=150),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='outside_handle',
            field=models.CharField(blank=True, help_text='Tay nắm cửa ngoài xe', max_length=150),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='pabs',
            field=models.CharField(blank=True, help_text='Hệ thống cân bằng góc chiếu ', max_length=150),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='position_light',
            field=models.CharField(blank=True, help_text='Đèn vị trí', max_length=150),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='rearlamp',
            field=models.CharField(blank=True, help_text='Đèn hậu', max_length=150),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='reverse_light',
            field=models.CharField(blank=True, help_text='Đèn lùi', max_length=150),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='self_adjust_reverse',
            field=models.BooleanField(default=False, help_text='Gương tự điều chỉnh khi lùi'),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='third_brake_lamp',
            field=models.CharField(blank=True, help_text='Đèn phanh trên cao, đèn phanh thứ 3', max_length=150),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='turn_signal_lamp',
            field=models.CharField(blank=True, help_text='Tích hợp đèn báo rẽ', max_length=150),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='wiper_front',
            field=models.CharField(blank=True, help_text='Gạt mưa trước', max_length=150),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='wiper_rear',
            field=models.CharField(blank=True, help_text='Gạt mưa sau', max_length=150),
        ),
        migrations.AlterField(
            model_name='interiorspecification',
            name='steering_adjust',
            field=models.CharField(blank=True, help_text='Điều chỉnh tay lái', max_length=100),
        ),
        migrations.AlterField(
            model_name='interiorspecification',
            name='steering_material',
            field=models.CharField(blank=True, help_text='Chất liệu tay lái', max_length=100),
        ),
        migrations.AlterField(
            model_name='interiorspecification',
            name='steering_type',
            field=models.CharField(blank=True, help_text='Loại tay lái', max_length=150),
        ),
        migrations.AlterField(
            model_name='performancespecification',
            name='brake',
            field=models.CharField(blank=True, help_text='Hệ thống phanh trước/sau(front/rear)', max_length=150),
        ),
        migrations.AlterField(
            model_name='performancespecification',
            name='brake_front',
            field=models.CharField(blank=True, help_text='Hệ thống phanh trước', max_length=150),
        ),
        migrations.AlterField(
            model_name='performancespecification',
            name='brake_rear',
            field=models.CharField(blank=True, help_text='Hệ thống phanh sau', max_length=150),
        ),
        migrations.AlterField(
            model_name='performancespecification',
            name='rim_type',
            field=models.CharField(blank=True, help_text='Loại vành', max_length=150),
        ),
        migrations.AlterField(
            model_name='performancespecification',
            name='spare_tire',
            field=models.CharField(blank=True, help_text='Lốp dự phòng', max_length=150),
        ),
        migrations.AlterField(
            model_name='performancespecification',
            name='suspension',
            field=models.CharField(blank=True, help_text='Hệ thống treo', max_length=200),
        ),
        migrations.AlterField(
            model_name='performancespecification',
            name='suspension_font',
            field=models.CharField(blank=True, help_text='Hệ thống treo trước', max_length=150),
        ),
        migrations.AlterField(
            model_name='performancespecification',
            name='suspension_rear',
            field=models.CharField(blank=True, help_text='Hệ thống treo sau', max_length=150),
        ),
        migrations.AlterField(
            model_name='performancespecification',
            name='tire_size',
            field=models.CharField(blank=True, help_text='Kích thước lốp xe', max_length=150),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='airbag',
            field=models.CharField(blank=True, help_text='Túi khí', max_length=100),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='child_safety_lock',
            field=models.CharField(blank=True, help_text='Khóa an toàn trẻ em', max_length=100),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='curtain_airbag',
            field=models.CharField(blank=True, help_text='Túi khí rèm', max_length=100),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='driver_knee_airbag',
            field=models.CharField(blank=True, help_text='Túi khí đầu gối người lái', max_length=100),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='font_airbag',
            field=models.CharField(blank=True, help_text='Túi khí phía trước', max_length=100),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='front_side_airbag',
            field=models.CharField(blank=True, help_text='Túi khí bên hông phía trước', max_length=100),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='parking_camera',
            field=models.CharField(blank=True, help_text='camera hỗ trợ đỗ xe', max_length=100),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='seat_belt',
            field=models.CharField(blank=True, help_text='Dây đai an toàn', max_length=100),
        ),
        migrations.AlterField(
            model_name='seatspecification',
            name='driver_seat',
            field=models.CharField(blank=True, help_text='Điều chỉnh ghế lái', max_length=100),
        ),
        migrations.AlterField(
            model_name='seatspecification',
            name='front_passeger_seat',
            field=models.CharField(blank=True, help_text='Điều chỉnh ghế hành khách', max_length=100),
        ),
        migrations.AlterField(
            model_name='seatspecification',
            name='front_seat_type',
            field=models.CharField(blank=True, help_text='Loại ghế trước', max_length=100),
        ),
        migrations.AlterField(
            model_name='seatspecification',
            name='rear_seat',
            field=models.CharField(blank=True, help_text='Ghế sau', max_length=100),
        ),
        migrations.AlterField(
            model_name='seatspecification',
            name='rear_seat_armset',
            field=models.CharField(blank=True, help_text='Tựa tay hàng ghế sau', max_length=100),
        ),
        migrations.AlterField(
            model_name='seatspecification',
            name='seat_material',
            field=models.CharField(blank=True, help_text='Chất liệu bọc ghế', max_length=100),
        ),
        migrations.AlterField(
            model_name='seatspecification',
            name='seat_memory',
            field=models.CharField(blank=True, help_text='Bộ nhớ vị trí ghế', max_length=100),
        ),
    ]
