# Generated by Django 6.0.6 on 2026-08-16 22:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_carmodel_created_at_carmodel_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Ưu tiên xuất hiện', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Chỉ số để ưu tiên hiển thị', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
            preserve_default=False,
        ),
    ]
