# Generated by Django 6.0.6 on 2026-08-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_brand_display_order_carmodel_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='carvariant',
            name='number_of_seats',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Số chỗ ngồi', null=True),
        ),
    ]
