# Generated by Django 6.0.6 on 2026-08-17 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_carvariant_number_of_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Ưu tiên xuất hiện', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Chỉ số để ưu tiên hiển thị', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
