# Generated by Django 6.0.6 on 2026-09-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_carimage_author_name_carimage_author_url_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='carimage',
            constraint=models.UniqueConstraint(condition=models.Q(('source_url', ''), _negated=True), fields=('car', 'source_url'), name='unique_car_image_source_url'),
        ),
        migrations.AddConstraint(
            model_name='variantimage',
            constraint=models.UniqueConstraint(condition=models.Q(('source_url', ''), _negated=True), fields=('variant', 'source_url'), name='unique_variant_image_source_url'),
        ),
    ]
