# Generated by Django 6.0.6 on 2026-09-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_carimage_unique_car_image_source_url_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='carimage',
            constraint=models.UniqueConstraint(fields=('car', 'image'), name='unique_car_image_path'),
        ),
        migrations.AddConstraint(
            model_name='variantimage',
            constraint=models.UniqueConstraint(fields=('variant', 'image'), name='unique_variant_image_path'),
        ),
    ]
