# Generated by Django 6.0.6 on 2026-09-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0020_carimage_unique_car_image_path_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comfortspecification',
            options={'verbose_name': 'Tiện Lợi', 'verbose_name_plural': 'Tiện Lợi'},
        ),
        migrations.AlterModelOptions(
            name='dimensionspecification',
            options={'verbose_name': 'Tổng Thể', 'verbose_name_plural': 'Tổng Thể'},
        ),
        migrations.AlterModelOptions(
            name='enginespecification',
            options={'verbose_name': 'Động Cơ', 'verbose_name_plural': 'Động Cơ'},
        ),
        migrations.AlterModelOptions(
            name='exteriorspecification',
            options={'verbose_name': 'Ngoại Thất', 'verbose_name_plural': 'Ngoại Thất'},
        ),
        migrations.AlterModelOptions(
            name='fuelconsumptionspecification',
            options={'verbose_name': 'Nhiên Liệu', 'verbose_name_plural': 'Nhiên Liệu'},
        ),
        migrations.AlterModelOptions(
            name='interiorspecification',
            options={'verbose_name': 'Nội Thất', 'verbose_name_plural': 'Nội Thất'},
        ),
        migrations.AlterModelOptions(
            name='performancespecification',
            options={'verbose_name': 'Vận Hành', 'verbose_name_plural': 'Vận Hành'},
        ),
        migrations.AlterModelOptions(
            name='safetyspecification',
            options={'verbose_name': 'An Toàn', 'verbose_name_plural': 'An Toàn'},
        ),
        migrations.AlterModelOptions(
            name='seatspecification',
            options={'verbose_name': 'Ghế Ngồi', 'verbose_name_plural': 'Ghế Ngồi'},
        ),
        migrations.AlterModelOptions(
            name='securespecification',
            options={'verbose_name': 'An Ninh', 'verbose_name_plural': 'An Ninh'},
        ),
        migrations.RenameField(
            model_name='exteriorspecification',
            old_name='nlm',
            new_name='navigation_light_mode',
        ),
        migrations.RemoveField(
            model_name='comfortspecification',
            name='number_of_speaker',
        ),
        migrations.RemoveField(
            model_name='comfortspecification',
            name='power_back_door',
        ),
        migrations.RemoveField(
            model_name='comfortspecification',
            name='usb_connect_front',
        ),
        migrations.RemoveField(
            model_name='comfortspecification',
            name='usb_connect_rear',
        ),
        migrations.RemoveField(
            model_name='exteriorspecification',
            name='bumper_bar_front',
        ),
        migrations.RemoveField(
            model_name='exteriorspecification',
            name='bumper_bar_rear',
        ),
        migrations.RemoveField(
            model_name='exteriorspecification',
            name='foglamp',
        ),
        migrations.RemoveField(
            model_name='exteriorspecification',
            name='hls',
        ),
        migrations.RemoveField(
            model_name='exteriorspecification',
            name='pabs',
        ),
        migrations.RemoveField(
            model_name='exteriorspecification',
            name='rear_glass_defrogger',
        ),
        migrations.RemoveField(
            model_name='interiorspecification',
            name='combination_metter',
        ),
        migrations.RemoveField(
            model_name='interiorspecification',
            name='metter_type',
        ),
        migrations.RemoveField(
            model_name='interiorspecification',
            name='power_steering',
        ),
        migrations.RemoveField(
            model_name='interiorspecification',
            name='sunroof',
        ),
        migrations.RemoveField(
            model_name='performancespecification',
            name='brake_front',
        ),
        migrations.RemoveField(
            model_name='performancespecification',
            name='brake_rear',
        ),
        migrations.RemoveField(
            model_name='performancespecification',
            name='rim_type',
        ),
        migrations.RemoveField(
            model_name='performancespecification',
            name='suspension_font',
        ),
        migrations.RemoveField(
            model_name='performancespecification',
            name='suspension_rear',
        ),
        migrations.RemoveField(
            model_name='performancespecification',
            name='tire_size',
        ),
        migrations.RemoveField(
            model_name='safetyspecification',
            name='ahb',
        ),
        migrations.RemoveField(
            model_name='safetyspecification',
            name='bsm',
        ),
        migrations.RemoveField(
            model_name='safetyspecification',
            name='curtain_airbag',
        ),
        migrations.RemoveField(
            model_name='safetyspecification',
            name='drcc',
        ),
        migrations.RemoveField(
            model_name='safetyspecification',
            name='driver_knee_airbag',
        ),
        migrations.RemoveField(
            model_name='safetyspecification',
            name='font_airbag',
        ),
        migrations.RemoveField(
            model_name='safetyspecification',
            name='front_side_airbag',
        ),
        migrations.RemoveField(
            model_name='safetyspecification',
            name='lda',
        ),
        migrations.RemoveField(
            model_name='safetyspecification',
            name='lta',
        ),
        migrations.RemoveField(
            model_name='safetyspecification',
            name='parking_camera',
        ),
        migrations.RemoveField(
            model_name='safetyspecification',
            name='pcs',
        ),
        migrations.RemoveField(
            model_name='safetyspecification',
            name='rcta',
        ),
        migrations.RemoveField(
            model_name='safetyspecification',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='safetyspecification',
            name='sensor_front',
        ),
        migrations.RemoveField(
            model_name='safetyspecification',
            name='sensor_front_corner',
        ),
        migrations.RemoveField(
            model_name='safetyspecification',
            name='sensor_rear',
        ),
        migrations.RemoveField(
            model_name='safetyspecification',
            name='sensor_rear_corner',
        ),
        migrations.RemoveField(
            model_name='safetyspecification',
            name='tpws',
        ),
        migrations.RemoveField(
            model_name='seatspecification',
            name='front_passeger_seat',
        ),
        migrations.RemoveField(
            model_name='seatspecification',
            name='rear_seat_armset',
        ),
        migrations.AddField(
            model_name='comfortspecification',
            name='car_trunk',
            field=models.CharField(blank=True, help_text='Cốp xe', max_length=200),
        ),
        migrations.AddField(
            model_name='comfortspecification',
            name='speaker',
            field=models.CharField(blank=True, help_text='Âm thanh', max_length=100),
        ),
        migrations.AddField(
            model_name='comfortspecification',
            name='usb_connect',
            field=models.CharField(blank=True, help_text='Kết nối usb', max_length=200),
        ),
        migrations.AddField(
            model_name='dimensionspecification',
            name='track_width',
            field=models.CharField(blank=True, help_text='Vết bánh xe trước/sau (mm)', max_length=50),
        ),
        migrations.AddField(
            model_name='exteriorspecification',
            name='mirror_heating',
            field=models.BooleanField(default=False, help_text='Sấy gương'),
        ),
        migrations.AddField(
            model_name='exteriorspecification',
            name='projection_angle_balance',
            field=models.CharField(blank=True, help_text='Hệ thống cân bằng góc chiếu (PABS)', max_length=150),
        ),
        migrations.AddField(
            model_name='exteriorspecification',
            name='rear_glass_defogger',
            field=models.BooleanField(default=False, help_text='Sấy kính sau'),
        ),
        migrations.AddField(
            model_name='exteriorspecification',
            name='sunroof',
            field=models.CharField(blank=True, help_text='Cửa sổ trời', max_length=100),
        ),
        migrations.AddField(
            model_name='interiorspecification',
            name='combination_meter',
            field=models.CharField(blank=True, help_text='Cụm đồng hồ', max_length=100),
        ),
        migrations.AddField(
            model_name='interiorspecification',
            name='meter_type',
            field=models.CharField(blank=True, help_text='Loại đồng hồ', max_length=100),
        ),
        migrations.AddField(
            model_name='performancespecification',
            name='rim',
            field=models.CharField(blank=True, help_text='Vành xe', max_length=150),
        ),
        migrations.AddField(
            model_name='performancespecification',
            name='tire',
            field=models.CharField(blank=True, help_text='Lốp xe', max_length=150),
        ),
        migrations.AddField(
            model_name='safetyspecification',
            name='auto_high_beam',
            field=models.CharField(blank=True, help_text='Đèn chiếu xa tự động (AHB)', max_length=200),
        ),
        migrations.AddField(
            model_name='safetyspecification',
            name='collision_avoidance',
            field=models.CharField(blank=True, help_text='Phòng tránh va chạm', max_length=300),
        ),
        migrations.AddField(
            model_name='safetyspecification',
            name='lane_keeping_assist',
            field=models.CharField(blank=True, help_text='Hỗ trợ làn đường', max_length=300),
        ),
        migrations.AddField(
            model_name='safetyspecification',
            name='parking_sensor',
            field=models.CharField(blank=True, help_text='Cảm biến hỗ trợ đỗ xe', max_length=300),
        ),
        migrations.AddField(
            model_name='seatspecification',
            name='front_passenger_seat',
            field=models.CharField(blank=True, help_text='Điều chỉnh ghế hành khách phía trước', max_length=200),
        ),
        migrations.AddField(
            model_name='seatspecification',
            name='rear_seat_armrest',
            field=models.CharField(blank=True, help_text='Tựa tay hàng ghế sau', max_length=150),
        ),
        migrations.AlterField(
            model_name='carvariant',
            name='fuel_type',
            field=models.CharField(choices=[('gasoline', 'Xăng'), ('diesel', 'Diesel'), ('electric', 'Điện'), ('hybrid', 'Hybrid'), ('phev', 'Plug-in Hybrid')], help_text='Loại nhiên liệu', max_length=20),
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='air_conditioner',
            field=models.CharField(blank=True, help_text='Hệ thống điều hòa', max_length=150),
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='bluetooth',
            field=models.BooleanField(default=False, help_text='Kết nối Bluetooth'),
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='brake_hold',
            field=models.BooleanField(default=False, help_text='Giữ phanh tự động (Auto Hold)'),
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='control_rear_seat',
            field=models.BooleanField(default=False, help_text='Điều khiển từ hàng ghế sau'),
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='cruise_control',
            field=models.CharField(blank=True, help_text='Điều khiển hành trình', max_length=200),
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='display',
            field=models.CharField(blank=True, help_text='Màn hình giải trí', max_length=200),
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='display_info_windsheld',
            field=models.BooleanField(default=False, help_text='Hiển thị thông tin trên kính lái (HUD)'),
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='electric_parking_brake',
            field=models.BooleanField(default=False, help_text='Phanh tay điện tử (EPB)'),
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='hands_free_calling',
            field=models.BooleanField(default=False, help_text='Đàm thoại rảnh tay'),
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='power_window',
            field=models.CharField(blank=True, help_text='Cửa sổ điều chỉnh điện', max_length=150),
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='rear_air_duct',
            field=models.BooleanField(default=False, help_text='Cửa gió hàng ghế sau'),
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='rear_door_sunshade',
            field=models.CharField(blank=True, help_text='Rèm che nắng cửa sau', max_length=150),
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='rear_window_sunshade',
            field=models.CharField(blank=True, help_text='Rèm che nắng kính sau', max_length=150),
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='remote_door',
            field=models.BooleanField(default=False, help_text='Khóa cửa từ xa'),
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='smart_connect',
            field=models.CharField(blank=True, help_text='Kết nối thông minh', max_length=200),
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='smart_key',
            field=models.BooleanField(default=False, help_text='Chìa khóa thông minh & khởi động nút bấm'),
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='smart_mobile_connect',
            field=models.BooleanField(default=False, help_text='Kết nối điện thoại thông minh'),
        ),
        migrations.AlterField(
            model_name='comfortspecification',
            name='voice_control',
            field=models.BooleanField(default=False, help_text='Điều khiển bằng giọng nói'),
        ),
        migrations.AlterField(
            model_name='dimensionspecification',
            name='fuel_tank_capacity',
            field=models.CharField(blank=True, help_text='Dung tích bình nhiên liệu (Lít)', max_length=150),
        ),
        migrations.AlterField(
            model_name='dimensionspecification',
            name='full_loaded_weight',
            field=models.CharField(blank=True, help_text='Trọng lượng toàn tải (kg)', max_length=150),
        ),
        migrations.AlterField(
            model_name='dimensionspecification',
            name='ground_clearance',
            field=models.CharField(blank=True, help_text='Khoảng sáng gầm xe (mm)', max_length=150),
        ),
        migrations.AlterField(
            model_name='dimensionspecification',
            name='height',
            field=models.CharField(blank=True, default='', help_text='Chiều cao (mm)', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dimensionspecification',
            name='length',
            field=models.CharField(blank=True, default='', help_text='Chiều dài (mm)', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dimensionspecification',
            name='overall_dimensions',
            field=models.CharField(blank=True, help_text='Kích thước tổng thể (DxRxC) (mm)', max_length=100),
        ),
        migrations.AlterField(
            model_name='dimensionspecification',
            name='seating_capacity',
            field=models.CharField(blank=True, help_text='Số chỗ ngồi', max_length=150),
        ),
        migrations.AlterField(
            model_name='dimensionspecification',
            name='turning_radius',
            field=models.CharField(blank=True, help_text='Bán kính quay vòng tối thiểu (m)', max_length=50),
        ),
        migrations.AlterField(
            model_name='dimensionspecification',
            name='unloaded_weight',
            field=models.CharField(blank=True, help_text='Trọng lượng không tải (kg)', max_length=150),
        ),
        migrations.AlterField(
            model_name='dimensionspecification',
            name='wheelbase',
            field=models.CharField(blank=True, help_text='Chiều dài cơ sở (mm)', max_length=50),
        ),
        migrations.AlterField(
            model_name='dimensionspecification',
            name='width',
            field=models.CharField(blank=True, default='', help_text='Chiều rộng (mm)', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enginespecification',
            name='compression_ratio',
            field=models.CharField(blank=True, help_text='Tỉ số nén', max_length=50),
        ),
        migrations.AlterField(
            model_name='enginespecification',
            name='displacement',
            field=models.CharField(blank=True, help_text='Dung tích xy lanh (cc)', max_length=100),
        ),
        migrations.AlterField(
            model_name='enginespecification',
            name='drive_mode',
            field=models.CharField(blank=True, help_text='Các chế độ lái', max_length=200),
        ),
        migrations.AlterField(
            model_name='enginespecification',
            name='drive_train',
            field=models.CharField(blank=True, help_text='Hệ thống dẫn động', max_length=150),
        ),
        migrations.AlterField(
            model_name='enginespecification',
            name='electric_motor_mp',
            field=models.CharField(blank=True, help_text='Công suất tối đa động cơ điện', max_length=150),
        ),
        migrations.AlterField(
            model_name='enginespecification',
            name='electric_motor_mt',
            field=models.CharField(blank=True, help_text='Mô men xoắn tối đa động cơ điện', max_length=150),
        ),
        migrations.AlterField(
            model_name='enginespecification',
            name='engine_type',
            field=models.CharField(blank=True, help_text='Loại động cơ', max_length=150),
        ),
        migrations.AlterField(
            model_name='enginespecification',
            name='max_power',
            field=models.CharField(blank=True, help_text='Công suất tối đa', max_length=150),
        ),
        migrations.AlterField(
            model_name='enginespecification',
            name='max_torque',
            field=models.CharField(blank=True, help_text='Mô men xoắn cực đại', max_length=150),
        ),
        migrations.AlterField(
            model_name='enginespecification',
            name='number_of_cylinders',
            field=models.CharField(blank=True, help_text='Số xy lanh', max_length=50),
        ),
        migrations.AlterField(
            model_name='enginespecification',
            name='transmission',
            field=models.CharField(blank=True, choices=[('automatic', 'Tự động'), ('manual', 'Số sàn'), ('cvt', 'CVT'), ('dct', 'Ly hợp kép'), ('other', 'Khác')], help_text='Hộp số', max_length=150),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='auto_light_control',
            field=models.BooleanField(default=False, help_text='Tự động bật/tắt đèn'),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='bumper_bar',
            field=models.CharField(blank=True, help_text='Thanh cản', max_length=200),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='daytime_running_light',
            field=models.CharField(blank=True, help_text='Đèn chiếu sáng ban ngày (DRL)', max_length=150),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='headlamp',
            field=models.CharField(blank=True, help_text='Cụm đèn chiếu sáng trước', max_length=200),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='itsl',
            field=models.BooleanField(default=False, help_text='Tích hợp đèn báo rẽ trên gương'),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='light_on_reminder',
            field=models.BooleanField(default=False, help_text='Nhắc nhở đèn sáng'),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='low_beam_headlight',
            field=models.CharField(blank=True, help_text='Đèn chiếu gần', max_length=150),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='mirror',
            field=models.CharField(blank=True, help_text='Gương chiếu hậu ngoài', max_length=200),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='outside_handle',
            field=models.CharField(blank=True, help_text='Tay nắm cửa ngoài', max_length=150),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='power_adjust_mirror',
            field=models.BooleanField(default=False, help_text='Chỉnh điện'),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='rearlamp',
            field=models.CharField(blank=True, help_text='Cụm đèn hậu', max_length=200),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='self_adjust_reverse',
            field=models.BooleanField(default=False, help_text='Tự điều chỉnh khi lùi'),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='support_bar',
            field=models.BooleanField(default=False, help_text='Thanh đỡ nóc xe (giá nóc)'),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='third_brake_lamp',
            field=models.CharField(blank=True, help_text='Đèn phanh trên cao', max_length=150),
        ),
        migrations.AlterField(
            model_name='exteriorspecification',
            name='turn_signal_lamp',
            field=models.CharField(blank=True, help_text='Đèn báo rẽ', max_length=150),
        ),
        migrations.AlterField(
            model_name='fuelconsumptionspecification',
            name='combined',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mức tiêu thụ kết hợp (L/100km)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='fuelconsumptionspecification',
            name='emission_standards',
            field=models.CharField(blank=True, help_text='Tiêu chuẩn khí thải', max_length=100),
        ),
        migrations.AlterField(
            model_name='fuelconsumptionspecification',
            name='extra_urban',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mức tiêu thụ ngoài đô thị (L/100km)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='fuelconsumptionspecification',
            name='urban',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mức tiêu thụ trong đô thị (L/100km)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='interiorspecification',
            name='icb',
            field=models.CharField(blank=True, help_text='Nút bấm điều khiển tích hợp trên vô lăng', max_length=200),
        ),
        migrations.AlterField(
            model_name='interiorspecification',
            name='inner_mirror',
            field=models.CharField(blank=True, help_text='Gương chiếu hậu trong', max_length=100),
        ),
        migrations.AlterField(
            model_name='interiorspecification',
            name='inside_handle_door',
            field=models.CharField(blank=True, help_text='Tay nắm cửa trong', max_length=100),
        ),
        migrations.AlterField(
            model_name='interiorspecification',
            name='multi_info_display',
            field=models.CharField(blank=True, help_text='Màn hình hiển thị đa thông tin', max_length=150),
        ),
        migrations.AlterField(
            model_name='interiorspecification',
            name='paddle_shifter',
            field=models.BooleanField(default=False, help_text='Lẫy chuyển số sau vô lăng'),
        ),
        migrations.AlterField(
            model_name='performancespecification',
            name='brake',
            field=models.CharField(blank=True, help_text='Hệ thống phanh', max_length=300),
        ),
        migrations.AlterField(
            model_name='performancespecification',
            name='suspension',
            field=models.CharField(blank=True, help_text='Hệ thống treo', max_length=300),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='abs',
            field=models.BooleanField(default=False, help_text='Chống bó cứng phanh (ABS)'),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='airbag',
            field=models.CharField(blank=True, help_text='Túi khí', max_length=300),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='ba',
            field=models.BooleanField(default=False, help_text='Hỗ trợ lực phanh khẩn cấp (BA)'),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='camera_360',
            field=models.BooleanField(default=False, help_text='Camera 360 độ'),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='child_safety_lock',
            field=models.CharField(blank=True, help_text='Khóa an toàn trẻ em (ISOFIX)', max_length=150),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='ebd',
            field=models.BooleanField(default=False, help_text='Phân phối lực phanh điện tử (EBD)'),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='ebs',
            field=models.BooleanField(default=False, help_text='Đèn báo phanh khẩn cấp (EBS)'),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='exit_safety',
            field=models.BooleanField(default=False, help_text='Hỗ trợ ra khỏi xe an toàn (SEA/SEW)'),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='hac',
            field=models.BooleanField(default=False, help_text='Hỗ trợ khởi hành ngang dốc (HAC)'),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='parking_brake',
            field=models.BooleanField(default=False, help_text='Phanh hỗ trợ đỗ xe (PKSB)'),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='safety_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Số sao NCAP', null=True),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='seat_belt',
            field=models.CharField(blank=True, help_text='Dây đai an toàn', max_length=200),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='tpms',
            field=models.BooleanField(default=False, help_text='Cảnh báo áp suất lốp (TPMS)'),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='trc',
            field=models.BooleanField(default=False, help_text='Kiểm soát lực kéo (TRC/TCS)'),
        ),
        migrations.AlterField(
            model_name='safetyspecification',
            name='vsc',
            field=models.BooleanField(default=False, help_text='Cân bằng điện tử (VSC/ESC)'),
        ),
        migrations.AlterField(
            model_name='seatspecification',
            name='driver_seat',
            field=models.CharField(blank=True, help_text='Điều chỉnh ghế lái', max_length=200),
        ),
        migrations.AlterField(
            model_name='seatspecification',
            name='front_seat_type',
            field=models.CharField(blank=True, help_text='Loại ghế trước', max_length=150),
        ),
        migrations.AlterField(
            model_name='seatspecification',
            name='rear_seat',
            field=models.CharField(blank=True, help_text='Ghế sau', max_length=200),
        ),
        migrations.AlterField(
            model_name='seatspecification',
            name='seat_material',
            field=models.CharField(blank=True, help_text='Chất liệu bọc ghế', max_length=150),
        ),
        migrations.AlterField(
            model_name='seatspecification',
            name='seat_memory',
            field=models.CharField(blank=True, help_text='Bộ nhớ vị trí ghế', max_length=150),
        ),
        migrations.AlterField(
            model_name='seatspecification',
            name='seat_type',
            field=models.CharField(blank=True, help_text='Loại ghế', max_length=150),
        ),
        migrations.AlterField(
            model_name='seatspecification',
            name='second_seat',
            field=models.CharField(blank=True, help_text='Hàng ghế thứ hai', max_length=200),
        ),
        migrations.AlterField(
            model_name='seatspecification',
            name='third_seat',
            field=models.CharField(blank=True, help_text='Hàng ghế thứ ba', max_length=200),
        ),
        migrations.AlterField(
            model_name='securespecification',
            name='alarm_system',
            field=models.BooleanField(default=False, help_text='Hệ thống báo động'),
        ),
        migrations.AlterField(
            model_name='securespecification',
            name='eis',
            field=models.BooleanField(default=False, help_text='Mã hóa khóa động cơ (Immobilizer)'),
        ),
    ]
